### ISSUE TITLE
long term solution to packaging babel

### ISSUE THREAD

**Issue by sandys** [Daniel15/babel-standalone#1]
hi Daniel,
probably you and I are the only ones interested in this conversation (https://github.com/babel/babel/commit/c0afdfd1a83aab0c25a1fc23cee0b09d560f4d35). do you think Requirejs is a viable long term solution for people looking at a pure browser based flow ? 

or do you think we should start looking at alternatives. I'm not sure if you will maintain babel-standalone in the long term.

**Comment by finom** [comment]
There are more people interested in babel-browser. You're not alone. Dev versions for all my projects for the last months are powered by babel-browser.

**Comment by kapitancho** [comment]
Count me in. I would be happy to find an adequate solution for this problem. I wrote a comment in the same conversation and I would be happy to hear your feedback!

**Comment by jubishop** [comment]
I've just been looking into this myself, trying to make a standalone Rack middleware layer for my Ruby server.  Thanks for making this.

**Comment by jubishop** [comment]
btw I can get this working from within ruby like so:

js_code = ExecJS.compile(File.read('babel.js'))

babel_code = js_code.call(
  'Babel.transform',
  File.read('./public/js/jubiku.js'),
  {'presets' => ['es2015'], 'ast' => false}
)['code']

just replace that ./public/js/jubiku.js with whatever file you want to transpire.

**Comment by Daniel15** [comment]
@jubishop  - You might be interested in https://github.com/babel/ruby-babel-transpiler, which basically does just that.

**Comment by Daniel15** [comment]
>  do you think Requirejs is a viable long term solution for people looking at a pure browser based flow ?

I'm not sure, to be honest. At this point, the best long-term solution is probably to use Webpack or Browserify, as those seem to be the solutions most supported by the Babel team. While it's not a pure browser-based flow, Webpack's "watch" feature combined with live reloading is a pretty good development flow.

**Comment by jubishop** [comment]
Daniel, thanks for your reply.  I actually started by looking at that.  :)  Unfortunately it is still using the older version of babel.  your release is the only way i've found, right now, to use the most modern babel release from ruby.

**Comment by philmaker** [comment]
One reason why babel in the browser is so important is because of the concept of direct manipulation of code to see results. I shouldn't have a build process forced on me when I don't need it.

**Comment by Daniel15** [comment]
Closing this out. Automated builds will be the long-term solution for `babel-standalone` itself (#3)
