### ISSUE TITLE
API methods transformFile and transformFileSync

### ISSUE THREAD

**Issue by fbastian** [Daniel15/babel-standalone#12]
The README states that `babel.js` will expose the Babel API, but it seems that the methods `transformFile` and `transformFileSync` are not accessible (see http://babeljs.io/docs/usage/api/). Is there any plan to make these methods available?

**Comment by Daniel15** [comment]
This is intentional - File system APIs are specific to Node.js, whereas babel-standalone is designed to run in standalone contexts outside of Node.js. It doesn't have access to any native or Node-specific APIs.

**Comment by carrieje** [comment]
Any clue on how to compile a file then ?
I tried the following to compile my `scripts/index.js` file:
```
    <script type="text/javascript">
      var input = "require('scripts/index');"
      Babel.transform(input, { presets: ['es2015'] }).code;
    </script>
```

Maybe the answer is the same "No filesystem aspect".
But it is worth the question :-)

**Comment by Daniel15** [comment]
@carrieje - Ah, parsing of `script` tags with `text/babel` type is a good idea, I'll create a separate issue for that.

 `Babel.transform` just returns the transformed code, it does not actually execute it. You could execute it with `eval`.

**Comment by carrieje** [comment]
Yeah ! it would  be great !
Thank you.

Last detail, why this code produces `ReferenceError: require is not defined` ?
```
    <script type="text/javascript">
      var input = "require('script/index');"
      eval(Babel.transform(input, { presets: ['es2015'] }).code)
    </script>
```

Are the original issue and this, related ? Meaning related to "no filesystem" concept ?

**Comment by Daniel15** [comment]
That's right. `require` is mostly a NodeJS concept. Browsers don't have a `require` function built-in, so `require` doesn't do anything if you just try to use it by itself :) . You'd need to use some script that adds a require function (for example, RequireJS), or some other way of loading the code (for example, doing an AJAX request).

**Comment by carrieje** [comment]
:+1:

**Comment by fbastian** [comment]
> parsing of script tags with text/babel type is a good idea,
+1, this is basically what I wanted to achieve and why I opened this issue.
