### ISSUE TITLE
Bower support is missing

### ISSUE THREAD

**Issue by antivanov** [Daniel15/babel-standalone#14]
Currently the Bower support is missing which complicates the installation process.

One way of enabling Bower support is to have the built artifacts published to the main repository as some projects do, however this was not deemed appropriate https://github.com/Daniel15/babel-standalone/pull/13

Another way is to create a separate "artifact" repository/project that will contain the built artifacts of `babel-standalone` automatically pushed there by the build process of the main project. Then the published Bower package will refer to this "artifact" repository.

`babel-standalone` is meant to be used in a browser and Bower is quite a common tool used to install browser dependencies, so the support for it is highly desirable.

**Comment by danmartinez101** [comment]
`bower install https://npmcdn.com/babel-standalone@6.4.4` should do the trick for you.

**Comment by antivanov** [comment]
Thank you, for some reason I get an error message, might be related to the network configuration or Bower version I am using (1.7.2):

```
bower babel-standalone@6.4#*    cached https://npmcdn.com/babel-standalone@6.4.4
bower babel-standalone@6.4#*  validate https://npmcdn.com/babel-standalone@6.4.4#*
bower                        ENOTFOUND Package babel-standalone@6.4=https://npmcdn.com/babel-standalone@6.4.4 not found
```

In any case it might be nice to have an official Bower package.

**Comment by Daniel15** [comment]
I added Bower support, you should be able to `bower install babel-standalone`. Bower pulls directly from a Git repo, so I had to create a separate repo to contain the build artifacts (https://github.com/Daniel15/babel-standalone-bower). I didn't want them clogging up the main repo - A Git repo is not the right place for build artifacts!

**Comment by antivanov** [comment]
Thanks a lot for implementing Bower support. It is quite important since babel-standalone is mostly used in a browser environment.
