### ISSUE TITLE
Add ability to handle scripts using `text/babel` type

### ISSUE THREAD

**Issue by Daniel15** [Daniel15/babel-standalone#15]
As a simple example:

```
<script type="text/babel">
const foo = () => alert('Hello world!');
foo();
</script>
```

`babel-standalone` should provide some way to parse all `text/babel` script tags, transform the script using Babel, and evaluate their contents.

**Comment by danmartinez101** [comment]
https://github.com/danmartinez101/throw-in-the-towel/blob/master/index.js

I built this based on babel-standalone. This is basically the only addition I made on top of babel-standalone.

I'd be ecstatic to submit a PR for this and deprecate throw-in-the-towel. Let me know what you think!

**Comment by peterjuras** [comment]
That looks great! Any update on a PR?

**Comment by danmartinez101** [comment]
I'm still happy to create a PR for this if @Daniel15 would like to integrate something like it.

**Comment by Daniel15** [comment]
Sure, I'd appreciate a pull request :smile:

**Comment by gutenye** [comment]
Any updates? I believe a lot of developers need this feature since Babel 6 does not support it.

**Comment by Daniel15** [comment]
Release in babel-standalone 6.10.3.

**Comment by dublinus** [comment]
Is it possible to do this for a page which was loaded with ajax?

**Comment by Daniel15** [comment]
@dublinus  How are you doing your AJAX request? Most likely you should just use `Babel.transform` on the scripts directly.

**Comment by dublinus** [comment]
@Daniel15 That's what I ended up doing. Thanks!
