### ISSUE TITLE
Upgrade path from babel-core.browser

### ISSUE THREAD

**Issue by peterjuras** [Daniel15/babel-standalone#16]
Hi!

I wanted to ask what the recommended upgrade path is to have on-the-fly compilation in the browser. Previously, I would use ```babel-core.5.8.34``` like this:

```html
<script src="babel-core.5.8.34.browser.js"></script>
<script src"mysource.js" type="text/babel"></script>
```

```mysource.js``` would now be automatically compiled and executed. How can I achieve this with babel-standalone?

**Comment by danmartinez101** [comment]
https://github.com/Daniel15/babel-standalone/issues/15
