### ISSUE TITLE
JSX tranformation is slow

### ISSUE THREAD

**Issue by NerdGGuy** [Daniel15/babel-standalone#17]
Seems almost unusable on a mobile device. Completely different of course but I compared the jsx transformation to a browser version of html2hscript which seems to perform much better.

http://jsperf.com/babel-jsx-vs-html2hscript

Probably not something that can be fixed in babel-standalone but thought it's worth mentioning since the use-cases are similar but we see a crazy difference in performance.

**Comment by Daniel15** [comment]
it might be worth testing with an older version of `babel-browser` (from prior 6.x releases, or even the 5.x version) and seeing how the performance compares. I don't think Babel is really designed to be run on a mobile device.

**Comment by NerdGGuy** [comment]
On further profiling (version 6) it appears the speed difference is primarily caused by babel doing an AST based transformation as opposed to html2hscript tokenizing. According to a react discussion https://github.com/facebook/react/issues/5497 babel 6 performs better then babel 5.

I guess there is not much that can be done about that as babel is not expected to fit this use-case and any improvements would need to be done somewhere in babel and the jsx plugin.
