### ISSUE TITLE
Rebuild for 6.7.4

### ISSUE THREAD

**Issue by loganfsmyth** [Daniel15/babel-standalone#25]
We've been getting reports in https://phabricator.babeljs.io/T7198 which appear to be because of minification. I _think_ the case people are hitting will no longer occur in 6.7.x so it'd be great to get a new version of this out, since I think the majority of cases where people are using Babel as a prebuilt package is through this module.

**Comment by Daniel15** [comment]
Thanks, I'll do this as soon as I'm at my computer. I've been meaning to
automate pushing new builds of babel-standalone as soon as new releases of
Babel come out, I'll try to get that done soon :)

**Comment by Daniel15** [comment]
I've published 6.7.4 to npm as well as the Github releases page (https://github.com/Daniel15/babel-standalone/releases/tag/release-6.7.4).
