### ISSUE TITLE
How to use Babel plugins with Babel Standalone?

### ISSUE THREAD

**Issue by ZaDarkSide** [Daniel15/babel-standalone#27]
I would like to use https://github.com/Naddiseo/babel-plugin-mjsx

Adding it to plugins array like this:

```js
	require.config({
		es6: {
			fileExtension: '.js'
		},
		babel: {
			presets: ['es2015'],
			plugins: ['transform-es2015-modules-amd', 'mjsx']
		},
	});
```

Gives error:

```
Error: Invalid plugin specified in Babel options: "mjsx"
```

**Comment by ZaDarkSide** [comment]
Well after some digging, I arrived at the conclusion that I must modify in this project ```gulpfile.js```

And add my plugin there like this:

```js
// All the presets we should bundle
export const availablePresets = {
...
'mithril-msx': {
		presets: [
			require("babel-preset-es2015"),
			require("babel-preset-react")
		],
		plugins: [
			require('babel-plugin-mjsx')
		]
...
```

**Comment by Daniel15** [comment]
You need to compile the plugin (eg. through Webpack or Browserify), and then pass it in the actual plugin itself.

Example:
```
Babel.transform(input, {
  presets: ['es2015'],
  plugins: [whateverExtraPluginYouWantToUse],
}).code;
```

Where `whateverExtraPluginYouWantToUse` is the actual plugin itself.
