### ISSUE TITLE
t.transform not a function with "systemjs": "~0.19.26",  "babel-standalone": "~6.7.4"

### ISSUE THREAD

**Issue by jkennerley** [Daniel15/babel-standalone#29]
getting this issue from chrome console ...
  system.js:4 Uncaught (in promise) Error: TypeError: t.transform is not a function(…)

This may relate to https://github.com/systemjs/systemjs/issues/891

I have this package json ...
{
  "name": "ASP.NET",
  "version": "0.0.0",
  "dependencies": {
    "angular2": "~2.0.0-beta.14",
    "systemjs": "~0.19.26"
  },
  "devDependencies": {
    "gulp": "3.9.1",
    "gulp-concat": "2.6.0",
    "gulp-cssmin": "0.1.7",
    "gulp-uglify": "1.5.3",
    "rimraf": "2.5.2",
    "typescript": "~1.8.9",
    "bootstrap": "^4.0.0-alpha.2",
    "es6-module-loader": "~0.17.11",
    "traceur": "~0.0.107",
    "babel-core": "~6.7.6",
    "babel-standalone": "~6.7.4"
  }
}

And, I have this web in script tag page

        var systemConfig = {
            transpiler: "babel",
            map: {
                "babel": "../lib/babel-standalone/babel.js"
            }
        };
        System.config(systemConfig);
        System.import("app.js");

**Comment by Daniel15** [comment]
I suspect this is an issue with SystemJS rather than babel-standalone. Please file this in the SystemJS repo. Thanks! :smile:
