### ISSUE TITLE
Automatic builds of latest (or all) Babel versions

### ISSUE THREAD

**Issue by daaain** [Daniel15/babel-standalone#3]
Hey,

I also think having this `browser.js` functionality is great for client only prototyping and examples on the web, so would be great to keep it running.

But it's not reasonable to keep this up to date manually, so maybe a good automatised build chain could take care of things? So I'm thinking something along the lines of [GreenKeeper](http://greenkeeper.io/) creating PRs of new versions of Babel, [Travis](https://travis-ci.com/) building a bundle and [CDNJS](https://cdnjs.com/) hosting all versions.

Is this something you'd be up for setting up? I wouldn't mind lending a hand and I'm sure others would be happy to chip in. All these services I mentioned should be free for open source projects.

**Comment by Daniel15** [comment]
Sure, I'm happy to set something up :) I'll take  a look at this soon.

**Comment by hzoo** [comment]
This would be great since we are using babel-standalone for the repl atm and it would be good for it to be updated to the latest release since its still on 6.7.7 (the last babel-standalone update). Even better maybe would be to have a dropdown for the last few versions for testing purposes.

Also, If you don't have as much time to maintain I can help with doing a release when we update babel before this is all setup.

**Comment by PeterDaveHello** [comment]
Is there any updates here? Thanks.

**Comment by Daniel15** [comment]
Yes, this is still something I'm going to implement.

@hzoo Every release is on CDNJS, we could easily show a dropdown on the
Babel REPL.

**Comment by LeonFedotov** [comment]
This would be great :+1:

**Comment by Daniel15** [comment]
I'm currently overseas but I've got some half-completed scripts for this on my home computer. I'll take a look and finish this once I'm back home :+1: 

I do have Greenkeeper configured for this repo, it never sends me any pull requests whenever new Babel versions come out though. I think it's broken or something.

**Comment by LeonFedotov** [comment]
Would you like to collaborate on that to advance this issue?

**Comment by hzoo** [comment]
Yeah maybe just need to debug why greenekeeper isn't working. Could also setup something like https://github.com/semantic-release/semantic-release

**Comment by Daniel15** [comment]
Initial work on an auto-update script: https://github.com/Daniel15/babel-standalone/commit/f82f8c7d6f7aabeebf6a6b99667141442178597c

I just need to add npm/bower push after update, and then I'll schedule it as a cronjob. :+1:

**Comment by Daniel15** [comment]
Mostly automated here: https://github.com/Daniel15/babel-standalone/blob/master/scripts/update.ps1

Currently automated:
 - Updating `package.json` to point to newest Babel packages
 - Building / running unit tests to ensure latest Babel version is still compatible
 - Updating version number in `package.json`
 - Committing changes to Git, and tagging them
 - Updating Bower repo based on files from NPM (https://github.com/Daniel15/babel-standalone-bower/blob/master/update.ps1)

The only thing left is to automate pushing to npm - I'm still doing that manually to verify that nothing is broken.

Given this is mostly done, I'm going to close this task out. 😄

**Comment by Daniel15** [comment]
Oh, I need to automate creation of the "release" on Github too, including uploading the `babel.js` and `babel.min.js` files. Writing this comment to remind myself.
