### ISSUE TITLE
Babel.transform fails when localStorage.debug = '*'

### ISSUE THREAD

**Issue by HQidea** [Daniel15/babel-standalone#30]
maybe should use `browser` field in package.json instead of `main` when `require('debug')`, but I am not sure whether it's a webpack bug

**Comment by Daniel15** [comment]
Do you get an error message?

**Comment by HQidea** [comment]
yes
```
Uncaught TypeError: unknown: Cannot read property 'write' of undefined(…)
log @ babel.js:38160
enabled @ babel.js:71978
debug @ babel.js:32676
parse @ babel.js:7665
parseCode @ babel.js:7755
(anonymous function) @ babel.js:33073
wrap @ babel.js:7715
transform @ babel.js:33071
transform @ babel.js:137
(anonymous function) @ VM809:1
_evaluateOn @ (program):145
_evaluateAndWrap @ (program):137
evaluate @ (program):118
```

**Comment by HQidea** [comment]
it also appears in https://babeljs.io/repl/

**Comment by Daniel15** [comment]
@HQidea  - Could you please provide instructions on how to replicate the issue on https://babeljs.io/repl/? I'm having trouble working out exactly where you're doing `localStorage.debug = '*'`.

**Comment by HQidea** [comment]
@Daniel15 
1. open https://babeljs.io/repl/
2. open console and set `localStorage.debug = '*'`
3. reload https://babeljs.io/repl/
4. all transforms fail

**Comment by HQidea** [comment]
@Daniel15 this issue is still there, the bundle file remains using Node.js version of visionmedia-debug

**Comment by Daniel15** [comment]
I haven't released a new version of babel-standalone yet. I'll do so once a new Babel version comes out.
