### ISSUE TITLE
Async/await plugin

### ISSUE THREAD

**Issue by congrady** [Daniel15/babel-standalone#32]
Hello, 
It might be a noob question, but is there a way to use a plugin for async/await in browser environment with babel standalone? Is babel standalone extendable? 
And if so, how would I do that?

Thanks

**Comment by Daniel15** [comment]
I think you need to also load `babel-polyfill` too, but it should work once you do that. Let me know if you encounter any issues :)

**Comment by Daniel15** [comment]
Closing this out, let me know if you still require assistance.
