### ISSUE TITLE
Use of additional plugins

### ISSUE THREAD

**Issue by gamtiq** [Daniel15/babel-standalone#38]
Hello,

Is it possible to use additional plugins besides those that are included in the build? For example, [add-module-exports](https://github.com/59naga/babel-plugin-add-module-exports).
If it is possible, how additional plugins can be used with `babel-standalone`?

**Comment by Daniel15** [comment]
You need to build the plugin separately (eg. ask the plugin author to provide a browser build), and then pass it in to your `Babel.transform` call.

```
// addModuleExports should be the plugin itself
var output = Babel.transform(input, { plugins: [ addModuleExports ] }).code;
```
