### ISSUE TITLE
Option to disable automatic "text/babel" script parsing

### ISSUE THREAD

**Issue by codewithmichael** [Daniel15/babel-standalone#39]
Issue #15 added the ability to auto-transpile `<script type="text/babel">` elements.

Could we get an option to disable that feature?

I use babel-standalone—6.7.7 via CDN—as the basis for one of my projects, [babel-browser-harness](https://github.com/codewithmichael/babel-browser-harness), that already transpiles `text/babel` script tags, along with providing a module loader and a number of other features.

I'd like to update BBH to use 6.10.3, but the only way I can do it right now is with a kind of ugly workaround that intercepts the `addEventListener()` method. External libraries are loaded from CDN by default, so I can't modify the babel-standalone script.

Since babel-standalone uses a window event listener on `DOMContentLoaded`, I was hoping you could add a method that could be used to remove the listener before the the event fires—something simple like:

```html
<script src=".../babel-standalone/6.10.3/babel.min.js"></script>
<script>
  Babel.removeDOMContentLoadedEventListener();
</script>
```

It should just require storing the event callback so it's available for `window.removeEventListener()`.

**Comment by Daniel15** [comment]
Good idea! Thanks for reporting.
