### ISSUE TITLE
Using with css modules

### ISSUE THREAD

**Issue by jakubzloczewski** [Daniel15/babel-standalone#41]
First of all thanks for this awesome library.
I got to the point where I need to load styles using css-modules.

Does anyone know how to use this library with css modules and less preprocessor? I've tried with babel-plugin-css-modules-transform, css-modules-require-hook, babel-plugin-webpack-loaders but all of them are requiring 'fs' what is not possible in browser.

Thanks,
Jakub

**Comment by Daniel15** [comment]
I don't think you'll be able to use CSS modules with Babel-standalone. It's only designed to process JavaScript files, not CSS files. Since it does not have access to the file system, it's limited in what it can do with regards to CSS files.
