### ISSUE TITLE
Safari treats const as var/let

### ISSUE THREAD

**Issue by OmgImAlexis** [Daniel15/babel-standalone#47]
Version: Safari 9.1 (11601.5.17.1).

````
const a = 1;
console.log(a); // 1
a = 2;
console.log(a); // 2
````

It also doesn't show the error that Chrome, etc. does.

**Comment by Daniel15** [comment]
This is probably an issue with Babel rather than babel-standalone, please report it as a Babel bug (https://phabricator.babeljs.io/).
