### ISSUE TITLE
`babel-plugin-external-helpers-2` was temporary and should be replaced by `babel-plugin-external-helpers`

### ISSUE THREAD

**Issue by cansin** [Daniel15/babel-standalone#61]
As the npm warning suggests:

```
npm WARN deprecated babel-plugin-external-helpers-2@6.3.13: This was a temporary package since the package name was already taken. The package name was transferred for babel so we recommend using babel-plugin-external-helpers instead.
```

I realized that while trying to use `babel-standalone` with a codebase that relies on `external-helpers` plugin rather than `external-helpers-2`.

**Comment by cansin** [comment]
I tried tackling the problem at https://github.com/Daniel15/babel-standalone/pull/62 .

**Comment by Daniel15** [comment]
Fixed in #62 - Thanks for your contribution!

**Comment by cansin** [comment]
@Daniel15 any change of releasing this as a build, so that I can start using it through npm? I couldn't figure out a way to npm install git repo directly and still trigger the build step, and I didn't want to clutter the npm repo with a duplicate package. Thank you!

**Comment by Daniel15** [comment]
@cansin - Babel-standalone's version numbers follow Babel's, so I only release new versions when new versions of Babel come out. Lucky for you, Babel 6.18.0 came out today, so I'll push an update 😄

**Comment by cansin** [comment]
@Daniel15 ha didn't realize :D Perfect!

**Comment by Daniel15** [comment]
Pushed 6.18.0!
